### ISSUE TITLE
ACPI files

### ISSUE THREAD

**Issue by stevedat** [Edwardwich/hp-DA1023nia-Hackintosh#3]
Does it apply for other Hp on similar i5 8265u?
Thanks.

**Comment by Edwardwich** [comment]
@stevedat  you can test but I think problem with SSDT or DSDT

**Comment by stevedat** [comment]
I tested and worked, except for battery status, which is mine is corrected. Others worked well. Not much diff that I could notice :)
Both lid.aml not working on Bigsur, just for Catalina.

**Comment by Edwardwich** [comment]
@stevedat what your hp model?

**Comment by Edwardwich** [comment]
you need DSDT full patch or ssdt

**Comment by stevedat** [comment]
Hp elitebook 830 G6
I5 8265U

**Comment by stevedat** [comment]
> you need DSDT full patch or ssdt
> 
> 

If full patch is great. 
Currently i use acpi of tookdes works. His is i5-8565u running Catalina.

**Comment by Edwardwich** [comment]
@stevedat for battery 
add smc battery manger kext and ec enable kext 
may be battery fix in Mac OS

**Comment by stevedat** [comment]
Just about appleALC kext have no input audio both internal and jack 3.5. Other things work for me. I can alternatively either use Bluetooth headset or iPhone as speaker for meeting and recording.

**Comment by Edwardwich** [comment]
@stevedat Realtek ALC236 ????

**Comment by stevedat** [comment]
> @stevedat Realtek ALC236 ????
> 
> 

Nope. ALC215 layout 18 supported, yet not fully working.

**Comment by Edwardwich** [comment]
@stevedat  add apple alc kext only 
don't usr VoodooHDA

**Comment by Edwardwich** [comment]
https://github.com/acidanthera/AppleALC/tree/master/Resources/ALC215 

see this
